### ISSUE TITLE
[3.0] Not showing - No error BL 2.79b

### ISSUE THREAD

**Issue by schroef** [c30ra/uv-align-distribute#11]
rv 3.0
bl 2.79b
osx 

Im trying to use it with with Blender 2.79 but nothing shows. No error in the console nothing. Installed the plugin using the master from here and dropped it in addon folder, it shows and is checked. Nothing???

**Comment by c30ra** [comment]
you don't have to use the master... you must download it from releases page or from the link in the description, however sorry if I didn't reply on blenderartists but I didn't get any notifications until yesterday.

**Comment by schroef** [comment]
Dont worry, i didnt get it either. THe forum isnt that good any more. Quite some big issues there.

Which version is the latest then? Normally the gitHUb i presume

**Comment by c30ra** [comment]
Yeah, you're not the first one, that comes with this issue. Not everyone read the description and most of the people use the big green button on GitHub. This button is aimed for developers only.

**Comment by schroef** [comment]
Not sure what you mean by this, I was referring to the link on ba and here. The big green button is the actual versiinm. If you have a sec version you should make a separate branch on GitHub, that's how it works. Most Dev guys make a list the of progress and out new stuff in a dedicated Dev branch

**Comment by c30ra** [comment]
![immagine](https://user-images.githubusercontent.com/16150836/40885818-f3df3956-672d-11e8-820b-84da60745d84.png)

I mean this one, if you use this to download the zip, it won't install, most people use this to download. Instead, if you followed the link in the description page you can't go wrong. For Branching, if you check already have dev branch and other ones 😄.
