### ISSUE TITLE
Blender 2.83 empty tool

### ISSUE THREAD

**Issue by SemiRukiya** [c30ra/uv-align-distribute#13]
Hello there! I was about to try this addon but after I install it, there's an empty space in the place the tool should be (at least I assume it should be there, I'm new into blender). Here's the screenshot: https://i.imgur.com/uCMnG34.png

**Comment by c30ra** [comment]
Be sure UV sync is disabled, and any error that appear on console are helpful to understand the problem

**Comment by SemiRukiya** [comment]
That was it... Sorry for the disturbance then.
