### ISSUE TITLE
Match Islands does nothing

### ISSUE THREAD

**Issue by Maker261** [c30ra/uv-align-distribute#18]
The "Match Islands" option doesn't seem to do the job at all....
the islands I want to combine them together are 100% similar, but the addon itself doesn't think so..
![Screenshot_2](https://user-images.githubusercontent.com/46901949/178114674-7aae5dea-df2b-468d-ac88-7d49e18e1686.png)
it may be the addon not working in 3.2 (despite not getting any errors when I installed it)

**Comment by c30ra** [comment]
Can you provide me a sample blend file, so I can test it? On my Blender 3.2 work

**Comment by Maker261** [comment]
> Can you provide me a sample blend file, so I can test it? On my Blender 3.2 work

huh
I was just about to do that, but then I wanted to do test out if it happens the same in a new project scene
oddly enough, only THEN it told me that I needed an active face selected
Completely forgot the correct way of using the addon 😅 
Its kinda weird how that error didn't show up in the project I was working on tho

so yeah, issue solved

**Comment by c30ra** [comment]
Yes, it's quote strange... If you have any problem, write me again!
