### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by Nerathe** [c30ra/uv-align-distribute#8]
Hello, i need help to install the addon, i don't know which file i have to select to install the Addon, i need help very very soon! Thank you!

**Comment by c30ra** [comment]
Hi, you have to download the zip file, then in blender go to preference->add-on-> install
In the dialog that open, select the zip files

**Comment by c30ra** [comment]
This is the link https://github.com/c30ra/uv-align-distribute/releases/latest

Sorry for the late reply, but I've received the notification only now...

**Comment by Nerathe** [comment]
But which file i have to select to install?

**Comment by Nerathe** [comment]
I tried to install, seems to be installed but i can't see the panel of the addon

**Comment by c30ra** [comment]
You dont need to select any file, just select the whole zip file in the dialog, blender will take care of the rest.. 
For the panel: 
* Check if you enabled the add on in the user preference
* do you have unwrapped the mesh??
* are you in edit mode with all faces selected?
* if everything is true, are you on any linux system(Linux is not supported)?
If anything doesn't work, open the blender Windows console and tell me any error you see

**Comment by Nerathe** [comment]
I enables, mesh unwrapped and faces selected, i don't use linux and the blender windows console doens't show any error.

**Comment by c30ra** [comment]
Unfortunately, if there are any errors I can't really say what it's the problem...

**Comment by Nerathe** [comment]
When i disable and enable the addon shows this:

Read new prefs: C:\Users\DarkZlekim\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend
found bundled python: D:\Blender\2.78\python
read blend: H:\CIFOG\escena_Clash Royale EXTREURE MAPES2.blend
trying to save userpref at C:\Users\DarkZlekim\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend ok
trying to save userpref at C:\Users\DarkZlekim\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend ok
<!> event has invalid window

**Comment by c30ra** [comment]
No errors as you said.. The only thing that comes in mind is if uv selection sync is enabled the panel will be hidden, because the addon is not made to work in this mode.

Also, try to press spacebar inside uv\image editor, and type align: If the addon is loaded correctly you should see something like this:

Uv:              Align top margin
Uv:              Align vertical axis
......
And so on
